In [2]:
import pandas as pd

pseries = pd.Series([3,-5,7,5])

pseries

0    3
1   -5
2    7
3    5
dtype: int64

In [3]:
pseries2 = pd.Series([3,-3,5,8],index=['a','b','c','d'])

pseries2

a    3
b   -3
c    5
d    8
dtype: int64

In [3]:
pseries.head()
pseries.describe()

count    4.000000
mean     2.500000
std      5.259911
min     -5.000000
25%      1.000000
50%      4.000000
75%      5.500000
max      7.000000
dtype: float64

In [5]:
pseries.size

4

In [6]:
media = (pseries2['a']+pseries2['d'])/2

media

5.5

In [7]:
media2 = (pseries[0]+pseries[3])/2
media2

4.0

In [4]:
pseries2.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [12]:
import pandas as pd

arquivo = pd.ExcelFile('1exdadosexcel.xlsx')
dados =   pd.read_excel(arquivo,'Plan1')
dados

       A  B  C  D
Maria  5  2  4  6
Bilbo  4  4  6  3
Sara   8  4  6  9
José   1  8  3  4

In [13]:
dados1 = dados
dados2 = dados
dados3 = dados
arquivo = pd.ExcelWriter('resultados.xlsx')

dados1.to_excel(arquivo,'dados1-RESULT')
dados2.to_excel(arquivo,'dados2-RESULT')
dados3.to_excel(arquivo,'dados3-RESULT')

arquivo.save()

In [20]:
import pandas as pd

arquivo1 = pd.read_csv('pesquisa.csv',sep=",")
dados4 = arquivo1
arquivo1

,Carimbo de data/hora,1) Qual é seu custo fixo em Jaboticabal ? (Se vc não sabe coloque um valor aproximado),2) Mestrado/ Doutorado ?
0,2018/08/21 10:00:43 AM GMT-3,1.5,Doutorado
1,2018/08/21 10:00:47 AM GMT-3,1200.0,Doutorado
2,2018/08/21 10:00:50 AM GMT-3,400.0,Doutorado
3,2018/08/21 10:00:50 AM GMT-3,800.0,Doutorado
4,2018/08/21 10:00:50 AM GMT-3,650.0,Mestrado
5,2018/08/21 10:00:53 AM GMT-3,700.0,Doutorado
6,2018/08/21 10:01:00 AM GMT-3,500.0,Mestrado
7,2018/08/21 10:01:02 AM GMT-3,800.0,Doutorado
8,2018/08/21 10:01:04 AM GMT-3,2.6,Doutorado
9,2018/08/21 10:01:09 AM GMT-3,650.0,Doutorado
10,2018/08/21 10:01:11 AM GMT-3,2500.0,Mestrado
11,2018/08/21 10:01:11 AM GMT-3,550.0,Doutorado
12,2018/08/21 10:01:11 AM GMT-3,900.0,Doutorado
13,2018/08/21 10:01:11 AM GMT-3,1.0,Mestrado
14,2018/08/21 10:01:12 AM GMT-3,1000.0,Doutorado
15,2018/08/21 10:01:12 AM GMT-3,1.6,Mestrado
16,2018/08/21 10:01:12 AM GMT-3,500.0,Mestrado
17,2018/08/21 10:01:12 AM GMT-3,1300.0,Mestrado
18,2018/08/21 10:01:13 AM GMT-3,700.0,Doutorado
19,2018/08/21 10:01:14 AM GMT-3,700.0,Doutorado
20,2018/08/21 10:01:15 AM GMT-3,1000.0,Doutorado
21,2018/08/21 10:01:18 AM GMT-3,900.0,Mestrado
22,2018/08/21 10:01:18 AM GMT-3,1000.0,Doutorado
23,2018/08/21 10:01:21 AM GMT-3,900.0,Doutorado
24,2018/08/21 10:01:21 AM GMT-3,1050.0,Doutorado
25,2018/08/21 10:01:23 AM GMT-3,1200.0,Doutorado
26,2018/08/21 10:01:25 AM GMT-3,2000.0,Doutorado
27,2018/08/21 10:01:28 AM GMT-3,550.0,Doutorado
28,2018/08/21 10:01:28 AM GMT-3,1500.0,Mestrado
29,2018/08/21 10:01:30 AM GMT-3,1900.0,Doutorado
30,2018/08/21 10:01:31 AM GMT-3,1.5,Mestrado
31,2018/08/21 10:01:31 AM GMT-3,1500.0,Doutorado
32,2018/08/21 10:01:32 AM GMT-3,1600.0,Mestrado
33,2018/08/21 10:01:40 AM GMT-3,1800.0,Doutorado
34,2018/08/21 10:01:45 AM GMT-3,1.6,Mestrado
35,2018/08/21 10:01:51 AM GMT-3,1500.0,Mestrado
36,2018/08/21 10:02:26 AM GMT-3,1400.0,Mestrado
37,2018/08/21 10:04:03 AM GMT-3,850.0,Doutorado
38,2018/08/21 10:04:25 AM GMT-3,1300.0,Mestrado
39,2018/08/21 10:19:29 AM GMT-3,1000.0,Mestrado

In [21]:
dados4.columns=['carimbo','custo','nivel']
dados4

                         carimbo   custo      nivel
0   2018/08/21 10:00:43 AM GMT-3     1.5  Doutorado
1   2018/08/21 10:00:47 AM GMT-3  1200.0  Doutorado
2   2018/08/21 10:00:50 AM GMT-3   400.0  Doutorado
3   2018/08/21 10:00:50 AM GMT-3   800.0  Doutorado
4   2018/08/21 10:00:50 AM GMT-3   650.0   Mestrado
5   2018/08/21 10:00:53 AM GMT-3   700.0  Doutorado
6   2018/08/21 10:01:00 AM GMT-3   500.0   Mestrado
7   2018/08/21 10:01:02 AM GMT-3   800.0  Doutorado
8   2018/08/21 10:01:04 AM GMT-3     2.6  Doutorado
9   2018/08/21 10:01:09 AM GMT-3   650.0  Doutorado
10  2018/08/21 10:01:11 AM GMT-3  2500.0   Mestrado
11  2018/08/21 10:01:11 AM GMT-3   550.0  Doutorado
12  2018/08/21 10:01:11 AM GMT-3   900.0  Doutorado
13  2018/08/21 10:01:11 AM GMT-3     1.0   Mestrado
14  2018/08/21 10:01:12 AM GMT-3  1000.0  Doutorado
15  2018/08/21 10:01:12 AM GMT-3     1.6   Mestrado
16  2018/08/21 10:01:12 AM GMT-3   500.0   Mestrado
17  2018/08/21 10:01:12 AM GMT-3  1300.0   Mestrado
18  2018/08/21 10:01:13 AM GMT-3   700.0  Doutorado
19  2018/08/21 10:01:14 AM GMT-3   700.0  Doutorado
20  2018/08/21 10:01:15 AM GMT-3  1000.0  Doutorado
21  2018/08/21 10:01:18 AM GMT-3   900.0   Mestrado
22  2018/08/21 10:01:18 AM GMT-3  1000.0  Doutorado
23  2018/08/21 10:01:21 AM GMT-3   900.0  Doutorado
24  2018/08/21 10:01:21 AM GMT-3  1050.0  Doutorado
25  2018/08/21 10:01:23 AM GMT-3  1200.0  Doutorado
26  2018/08/21 10:01:25 AM GMT-3  2000.0  Doutorado
27  2018/08/21 10:01:28 AM GMT-3   550.0  Doutorado
28  2018/08/21 10:01:28 AM GMT-3  1500.0   Mestrado
29  2018/08/21 10:01:30 AM GMT-3  1900.0  Doutorado
30  2018/08/21 10:01:31 AM GMT-3     1.5   Mestrado
31  2018/08/21 10:01:31 AM GMT-3  1500.0  Doutorado
32  2018/08/21 10:01:32 AM GMT-3  1600.0   Mestrado
33  2018/08/21 10:01:40 AM GMT-3  1800.0  Doutorado
34  2018/08/21 10:01:45 AM GMT-3     1.6   Mestrado
35  2018/08/21 10:01:51 AM GMT-3  1500.0   Mestrado
36  2018/08/21 10:02:26 AM GMT-3  1400.0   Mestrado
37  2018/08/21 10:04:03 AM GMT-3   850.0  Doutorado
38  2018/08/21 10:04:25 AM GMT-3  1300.0   Mestrado
39  2018/08/21 10:19:29 AM GMT-3  1000.0   Mestrado